//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateTopology {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateTopology.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue . . ..
        /// </summary>
        internal static string DebugPressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("DebugPressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED to update the following Publications:.
        /// </summary>
        internal static string FailedPublications {
            get {
                return ResourceManager.GetString("FailedPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED to determine status for the following Publications:.
        /// </summary>
        internal static string FailedPublicationsWhatIf {
            get {
                return ResourceManager.GetString("FailedPublicationsWhatIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}    Reason: {1}.
        /// </summary>
        internal static string FailureEntryWithReason {
            get {
                return ResourceManager.GetString("FailureEntryWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The -WhatIf parameter has been specified. NO CHANGES WILL BE MADE..
        /// </summary>
        internal static string NoChangesWillBeMade {
            get {
                return ResourceManager.GetString("NoChangesWillBeMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0} / {1} ({2:P0}%)           .
        /// </summary>
        internal static string ProgressText {
            get {
                return ResourceManager.GetString("ProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications that were updated:.
        /// </summary>
        internal static string PublicationsUpdated {
            get {
                return ResourceManager.GetString("PublicationsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications that would be updated:.
        /// </summary>
        internal static string PublicationsUpdatedWhatIf {
            get {
                return ResourceManager.GetString("PublicationsUpdatedWhatIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. {0} Publication(s) updated, {1} failed, {2} skipped..
        /// </summary>
        internal static string ResultSummary {
            get {
                return ResourceManager.GetString("ResultSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done analyzing. {0} Publication(s) would be updated. {2} would be skipped..
        /// </summary>
        internal static string ResultSummaryWhatIf {
            get {
                return ResourceManager.GetString("ResultSummaryWhatIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Publication(s) found. Updating Topology....
        /// </summary>
        internal static string StartSummary {
            get {
                return ResourceManager.GetString("StartSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Publication(s) found. Analyzing....
        /// </summary>
        internal static string StartSummaryWhatIf {
            get {
                return ResourceManager.GetString("StartSummaryWhatIf", resourceCulture);
            }
        }
    }
}
